### ISSUE TITLE
Way to sync github and kaggle

### ISSUE THREAD

**Issue by simonqueric** [ivadomed/lumbar-classification-rsna-challenge-2024#20]
There is a way to synchronize github and kaggle (described in this [kaggle discussion](https://www.kaggle.com/discussions/questions-and-answers/513040)). 
For now, I haven't tried it. I copy paste the instructions so that every team members can try it :

To automate the synchronization between Kaggle and GitHub, you can use GitHub Actions or a CI/CD pipeline. Here's a basic outline using GitHub Actions:

## 1. Create a GitHub Action Workflow:

- In your GitHub repository, go to the "Actions" tab.
- Click on "New workflow".
- Choose "set up a workflow yourself".

## 2. Add workflow yaml file

```
name: Sync Kaggle Notebooks

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install kaggle
      run: pip install kaggle

    - name: Download Kaggle notebook
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: kaggle kernels pull <KAGGLE_USERNAME>/<NOTEBOOK_NAME> -p .

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update Kaggle notebooks"
        git push
```

## 3. Set Kaggle API Credentials:

- Go to the settings of your GitHub repository.
- Under the "Secrets and variables" section, click on "Actions".
- Add two new repository secrets: KAGGLE_USERNAME and KAGGLE_KEY with your Kaggle API credentials.
